<?xml version="1.0" encoding="UTF-8"?>
<!-- this is a phing build file -->
<project name="MyMuseJ4" basedir="." default="copy_to_mymuseJ4_in_joomla">
        <property name="myversion" value="4.2" override="true" />


        <property name="joomladir" value="/var/www/html/mymuseJ4/joomla-cms" override="true" />
        <property name="testadmincomp"
                value="/var/www/html/mymuseJ4/joomla-cms/administrator/components/com_mymuse"
                override="true" />
        <property name="src" value="${project.basedir}" override="true" />


        <fileset dir="./site" id="site_files">
                <include name="**" />
        </fileset>
        <fileset dir="./administrator" id="admin_files">
                <include name="**" />
        </fileset>
        <fileset dir="./media" id="media_files">
                <include name="**" />
        </fileset>
        

        <fileset dir="${src}" id="allfiles">
                <include name="administrator/*" />
                <include name="site/*" />
                <include name="media/*" />
                <include name="mymuse.xml" />
        </fileset>

        <fileset dir="./modules/mod_mymuse_minicart" id="mod_minicart_files">
                <include name="**" />
        </fileset>

        <fileset dir="./modules/mod_mymuse_amplitude" id="mod_amplitude_files">
                <include name="**" />
        </fileset>

        <fileset dir="./tests" id="test_files">
                <include name="**" />
        </fileset>

 
        <!-- Copy Target -->
        <target name="copy_to_mymuseJ4_in_joomla" description="copy target">
                <echo>Copying files from working dir to mymuse...
                </echo>

                <!-- copy file="${src}/tests/JoomlaBrowser.php"
                        todir="${joomladir}/libraries/vendor/joomla-projects/joomla-browser/src" / -->
            
                <copy todir="${joomladir}/components/com_mymuse">
                      <fileset refid="site_files" />
                </copy>
                <copy todir="${joomladir}/administrator/components/com_mymuse">
                       <fileset refid="admin_files" />
                </copy>
                <copy todir="${joomladir}/media/com_mymuse">
                       <fileset refid="media_files" />
                </copy>
                <copy todir="${joomladir}/tests">
                       <fileset refid="test_files" />
                </copy>
                
                <!--  languages -->

                <copy file="${src}/administrator/language/en-GB/com_mymuse.sys.ini"
                        todir="${joomladir}/administrator/language/en-GB" />
                        
                <copy file="${src}/administrator/language/en-GB/com_mymuse.ini"
                        todir="${joomladir}/administrator/language/en-GB" />
                        
                <copy file="${src}/site/language/en-GB/com_mymuse.ini"
                        todir="${joomladir}/language/en-GB" />

                <!-- copy file="${src}/plugins/audio_jplayer/language/en-GB/plg_mymuse_audio_jplayer.ini"
                        todir="${joomladir}/administrator/language/en-GB" /> 
                <copy file="${src}/plugins/audio_jplayer/language/en-GB/plg_mymuse_audio_jplayer.sys.ini"
                        todir="${joomladir}/administrator/language/en-GB" /> 

                <copy file="${src}/plugins/audio_amplitude/language/en-GB/plg_mymuse_audio_amplitude.ini"
                        todir="${joomladir}/administrator/language/en-GB" /> 
                <copy file="${src}/plugins/audio_amplitude/language/en-GB/plg_mymuse_audio_amplitude.sys.ini"
                        todir="${joomladir}/administrator/language/en-GB" / --> 

                        
                <!-- plugins -->
                <!-- copy file="${src}/plugins/audio_jplayer/audio_jplayer.php"
                            todir="${joomladir}/plugins/mymuse/audio_jplayer" /> 
                <copy file="${src}/plugins/audio_jplayer/audio_jplayer.xml"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer" /> 
                <copy file="${src}/plugins/audio_jplayer/Jplayer.swf"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer" /> 
                <copy file="${src}/plugins/audio_jplayer/js/jplayer.playlist.min.js"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/js" /> 
                <copy file="${src}/plugins/audio_jplayer/js/jquery.jplayer.inspector.js"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/js" /> 
                <copy file="${src}/plugins/audio_jplayer/js/jquery.jplayer.min.js"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/js" /> 
                <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.css"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/skin" />
                 <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.orig.css"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/skin" />
                <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.rtl.css"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/skin" />
                <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.jpg"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/skin" />
                <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.seeking.gif"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/skin" />
                <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.video.play.png"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/skin" / -->

                <copy file="${src}/plugins/audio_amplitude/audio_amplitude.php"
                            todir="${joomladir}/plugins/mymuse/audio_amplitude" /> 
                <copy file="${src}/plugins/audio_amplitude/audio_amplitude.xml"
                            todir="${joomladir}/plugins/mymuse/audio_amplitude" /> 
                

                <copy file="${src}/plugins/user_mymuse/language/en-GB/plg_user_mymuse.ini"
                        todir="${joomladir}/administrator/language/en-GB" />
                <copy file="${src}/plugins/user_mymuse/language/en-GB/plg_user_mymuse.sys.ini"
                        todir="${joomladir}/administrator/language/en-GB" />
                <copy file="${src}/plugins/user_mymusenoreg/language/en-GB/plg_user_mymusenoreg.ini"
                        todir="${joomladir}/administrator/language/en-GB" />
                <copy file="${src}/plugins/user_mymusenoreg/language/en-GB/plg_user_mymusenoreg.sys.ini"
                        todir="${joomladir}/administrator/language/en-GB" />

                <copy file="${src}/plugins/user_mymuse/mymuse.xml"
                        todir="${joomladir}/plugins/user/mymuse" /> 
                <copy file="${src}/plugins/user_mymuse/mymuse.php"
                        todir="${joomladir}/plugins/user/mymuse" />
                <copy file="${src}/plugins/user_mymuse/profiles/profile.xml"
                        todir="${joomladir}/plugins/user/mymuse/profiles" />
                <copy file="${src}/plugins/user_mymuse/fields/tos.php"
                            todir="${joomladir}/plugins/user/mymuse/fields" /> 
                
                <copy file="${src}/plugins/user_mymusenoreg/mymusenoreg.xml"
                            todir="${joomladir}/plugins/user/mymusenoreg" /> 
                <copy file="${src}/plugins/user_mymusenoreg/mymusenoreg.php"
                            todir="${joomladir}/plugins/user/mymusenoreg" />
                 <copy file="${src}/plugins/user_mymusenoreg/profiles/profile.xml"
                            todir="${joomladir}/plugins/user/mymusenoreg/profiles" />
                <copy file="${src}/plugins/user_mymusenoreg/fields/tos.php"
                        todir="${joomladir}/plugins/user/mymusenoreg/fields" /> 

                <!--  modules -->
                <copy todir="${joomladir}/modules/mod_mymuse_minicart">
                        <fileset refid="mod_minicart_files" />
                </copy>

                <copy todir="${joomladir}/modules/mod_mymuse_amplitude">
                        <fileset refid="mod_amplitude_files" />
                </copy>
        </target>
</project>
