<?xml version="1.0" encoding="UTF-8"?>
<!-- this is a phing build file -->
<project name="MyMuseJ4" basedir="." default="copy_to_mymuseJ4_in_joomla">
        <property name="myversion" value="4.2" override="true" />

        <!--property name="test" value="/var/www/html/mymuse/joomla" override="true" / -->
        <!-- property name="testadmincomp"
                value="/var/www/html/mymuse/joomla/administrator/components/com_mymuse"
                override="true" / -->
        <property name="test" value="/var/www/html/mymuseJ4/joomla" override="true" />
        <property name="testadmincomp"
                value="/var/www/html/mymuseJ4/joomla/administrator/components/com_mymuse"
                override="true" />
        <property name="src" value="${project.basedir}" override="true" />


        <fileset dir="./site" id="site_files">
                <include name="**" />
        </fileset>
        <fileset dir="./administrator" id="admin_files">
                <include name="**" />
        </fileset>
        <fileset dir="./media" id="media_files">
                <include name="**" />
        </fileset>
        

        <fileset dir="${src}" id="allfiles">
                <include name="administrator/*" />
                <include name="site/*" />
                <include name="media/*" />
                <include name="mymuse.xml" />
        </fileset>
        


 
        <!-- Copy Target -->
        <target name="copy_to_mymuseJ4_in_joomla" description="copy target">
                <echo>Copying files from working dir to mymuse...
                </echo>
            
                <copy todir="${test}/components/com_mymuse">
                      <fileset refid="site_files" />
                </copy>
                <copy todir="${test}/administrator/components/com_mymuse">
                       <fileset refid="admin_files" />
                </copy>
                <copy todir="${test}/media/com_mymuse">
                       <fileset refid="media_files" />
                </copy>
                
                <!--  languages -->

                <copy file="${src}/administrator/language/en-GB/com_mymuse.sys.ini"
                        todir="${test}/administrator/language/en-GB" />
                        
                <copy file="${src}/administrator/language/en-GB/com_mymuse.ini"
                        todir="${test}/administrator/language/en-GB" />
                        
                <copy file="${src}/site/language/en-GB/com_mymuse.ini"
                        todir="${test}/language/en-GB" />

                <copy file="${src}/plugins/audio_jplayer/language/en-GB/plg_mymuse_audio_jplayer.ini"
                        todir="${test}/administrator/language/en-GB" /> 
                <copy file="${src}/plugins/audio_jplayer/language/en-GB/plg_mymuse_audio_jplayer.sys.ini"
                        todir="${test}/administrator/language/en-GB" /> 

                <copy file="${src}/plugins/audio_amplitude/language/en-GB/plg_mymuse_audio_amplitude.ini"
                        todir="${test}/administrator/language/en-GB" /> 
                <copy file="${src}/plugins/audio_amplitude/language/en-GB/plg_mymuse_audio_amplitude.sys.ini"
                        todir="${test}/administrator/language/en-GB" /> 

                        
                <!-- plugins -->
                <copy file="${src}/plugins/audio_jplayer/audio_jplayer.php"
                            todir="${test}/plugins/mymuse/audio_jplayer" /> 
                <copy file="${src}/plugins/audio_jplayer/audio_jplayer.xml"
                                todir="${test}/plugins/mymuse/audio_jplayer" /> 
                <copy file="${src}/plugins/audio_jplayer/Jplayer.swf"
                                todir="${test}/plugins/mymuse/audio_jplayer" /> 
                <copy file="${src}/plugins/audio_jplayer/js/jplayer.playlist.min.js"
                                todir="${test}/plugins/mymuse/audio_jplayer/js" /> 
                <copy file="${src}/plugins/audio_jplayer/js/jquery.jplayer.inspector.js"
                                todir="${test}/plugins/mymuse/audio_jplayer/js" /> 
                <copy file="${src}/plugins/audio_jplayer/js/jquery.jplayer.min.js"
                                todir="${test}/plugins/mymuse/audio_jplayer/js" /> 
                <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.css"
                                todir="${test}/plugins/mymuse/audio_jplayer/skin" />
                 <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.orig.css"
                                todir="${test}/plugins/mymuse/audio_jplayer/skin" />
                <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.rtl.css"
                                todir="${test}/plugins/mymuse/audio_jplayer/skin" />
                <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.jpg"
                                todir="${test}/plugins/mymuse/audio_jplayer/skin" />
                <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.seeking.gif"
                                todir="${test}/plugins/mymuse/audio_jplayer/skin" />
                <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.video.play.png"
                                todir="${test}/plugins/mymuse/audio_jplayer/skin" />

                <copy file="${src}/plugins/audio_amplitude/audio_amplitude.php"
                            todir="${test}/plugins/mymuse/audio_amplitude" /> 
                <copy file="${src}/plugins/audio_amplitude/audio_amplitude.xml"
                            todir="${test}/plugins/mymuse/audio_amplitude" /> 
                <copy file="${src}/plugins/audio_amplitude/js/amplitude.js"
                            todir="${test}/plugins/mymuse/audio_amplitude/js" /> 
                <copy file="${src}/plugins/audio_amplitude/assets/amplitude.css"
                            todir="${test}/plugins/mymuse/audio_amplitude/assets" /> 
                <copy file="${src}/plugins/audio_amplitude/js/amplitude.js.map"
                            todir="${test}/plugins/mymuse/audio_amplitude/js" /> 
                <copy file="${src}/plugins/audio_amplitude/js/amplitude.min.js"
                            todir="${test}/plugins/mymuse/audio_amplitude/js" /> 
                <copy file="${src}/plugins/audio_amplitude/js/visualizations/bar.js"
                            todir="${test}/plugins/mymuse/audio_amplitude/js/visualizations" /> 
                <copy file="${src}/plugins/audio_amplitude/js/visualizations/circular-equalizer.js"
                            todir="${test}/plugins/mymuse/audio_amplitude/js/visualizations" /> 
                <copy file="${src}/plugins/audio_amplitude/js/visualizations/frequencyanalyzer.js"
                            todir="${test}/plugins/mymuse/audio_amplitude/js/visualizations" /> 
                <copy file="${src}/plugins/audio_amplitude/js/visualizations/michaelbromley.js"
                            todir="${test}/plugins/mymuse/audio_amplitude/js/visualizations" /> 
                <copy file="${src}/plugins/audio_amplitude/js/visualizations/template.js"
                            todir="${test}/plugins/mymuse/audio_amplitude/js/visualizations" /> 

                <copy file="${src}/plugins/user_mymuse/language/en-GB/plg_user_mymuse.ini"
                        todir="${test}/administrator/language/en-GB" />
                <copy file="${src}/plugins/user_mymuse/language/en-GB/plg_user_mymuse.sys.ini"
                        todir="${test}/administrator/language/en-GB" />
                <copy file="${src}/plugins/user_mymusenoreg/language/en-GB/plg_user_mymusenoreg.ini"
                        todir="${test}/administrator/language/en-GB" />
                <copy file="${src}/plugins/user_mymusenoreg/language/en-GB/plg_user_mymusenoreg.sys.ini"
                        todir="${test}/administrator/language/en-GB" />

                <copy file="${src}/plugins/user_mymuse/mymuse.xml"
                        todir="${test}/plugins/user/mymuse" /> 
                <copy file="${src}/plugins/user_mymuse/mymuse.php"
                        todir="${test}/plugins/user/mymuse" />
                <copy file="${src}/plugins/user_mymuse/profiles/profile.xml"
                        todir="${test}/plugins/user/mymuse/profiles" />
                <copy file="${src}/plugins/user_mymuse/fields/tos.php"
                            todir="${test}/plugins/user/mymuse/fields" /> 
                
                <copy file="${src}/plugins/user_mymusenoreg/mymusenoreg.xml"
                            todir="${test}/plugins/user/mymusenoreg" /> 
                <copy file="${src}/plugins/user_mymusenoreg/mymusenoreg.php"
                            todir="${test}/plugins/user/mymusenoreg" />
                 <copy file="${src}/plugins/user_mymusenoreg/profiles/profile.xml"
                            todir="${test}/plugins/user/mymusenoreg/profiles" />
                <copy file="${src}/plugins/user_mymusenoreg/fields/tos.php"
                        todir="${test}/plugins/user/mymusenoreg/fields" /> 
        </target>
</project>
