<?xml version="1.0" encoding="UTF-8"?>
<!-- this is a phing build file -->
<project name="MyMuseJ4" basedir="." default="copy_to_mymuseJ4_in_joomla">
        <property name="myversion" value="4.2" override="true" />

<!-- /var/www/html/mymuseJ4/joomla-cms -->
<!-- /var/www/html/avonlea/brucegandymusic -->
<!-- /var/www/html/singsong/live -->
        <property name="joomladir" value="/var/www/html/mymuseJ4/joomla-cms" override="true" />
        <property name="testadmincomp"
                value="/var/www/html/mymuseJ4/joomla-cms/administrator/components/com_mymuse"
                override="true" />
        <property name="src" value="${project.basedir}" override="true" />


        <fileset dir="./site" id="site_files">
                <include name="**" />
        </fileset>
        <fileset dir="./administrator" id="admin_files">
                <include name="**" />
        </fileset>
        <fileset dir="./media" id="media_files">
                <include name="**" />
        </fileset>
        

        <fileset dir="${src}" id="allfiles">
                <include name="administrator/*" />
                <include name="site/*" />
                <include name="media/*" />
                <include name="mymuse.xml" />
        </fileset>

        <fileset dir="./modules/mod_mymuse_minicart" id="mod_minicart_files">
                <include name="**" />
        </fileset>

        <fileset dir="./modules/mod_mymuse_amplitude" id="mod_amplitude_files">
                <include name="**" />
        </fileset>

        <fileset dir="./modules/mod_mymuse_latest" id="mod_latest_files">
                <include name="**" />
        </fileset>

        <fileset dir="./tests" id="test_files">
                <include name="**" />
        </fileset>

 
        <!-- Copy Target -->
        <target name="copy_to_mymuseJ4_in_joomla" description="copy target">
                <echo>Copying files from working dir to mymuse...
                </echo>

                <!-- copy file="${src}/tests/JoomlaBrowser.php"
                        todir="${joomladir}/libraries/vendor/joomla-projects/joomla-browser/src" / -->
            
                <copy todir="${joomladir}/components/com_mymuse">
                      <fileset refid="site_files" />
                </copy>
                <copy todir="${joomladir}/administrator/components/com_mymuse">
                       <fileset refid="admin_files" />
                </copy>
                <copy todir="${joomladir}/media/com_mymuse">
                       <fileset refid="media_files" />
                </copy>
                <copy todir="${joomladir}/tests">
                       <fileset refid="test_files" />
                </copy>
                
                <!--  languages -->

                <copy file="${src}/administrator/language/en-GB/com_mymuse.sys.ini"
                        todir="${joomladir}/administrator/language/en-GB" />
                        
                <copy file="${src}/administrator/language/en-GB/com_mymuse.ini"
                        todir="${joomladir}/administrator/language/en-GB" />
                        
                <copy file="${src}/site/language/en-GB/com_mymuse.ini"
                        todir="${joomladir}/language/en-GB" />

                <!-- copy file="${src}/plugins/audio_jplayer/language/en-GB/plg_mymuse_audio_jplayer.ini"
                        todir="${joomladir}/administrator/language/en-GB" /> 
                <copy file="${src}/plugins/audio_jplayer/language/en-GB/plg_mymuse_audio_jplayer.sys.ini"
                        todir="${joomladir}/administrator/language/en-GB" /> 
                -->

                <copy file="${src}/plugins/audio_amplitude/language/en-GB/plg_mymuse_audio_amplitude.ini"
                        todir="${joomladir}/administrator/language/en-GB" /> 
                <copy file="${src}/plugins/audio_amplitude/language/en-GB/plg_mymuse_audio_amplitude.sys.ini"
                        todir="${joomladir}/administrator/language/en-GB" /> 

                <copy file="${src}/plugins/products/language/en-GB/plg_finder_products.ini"
                        todir="${joomladir}/administrator/language/en-GB" /> 
                <copy file="${src}/plugins/products/language/en-GB/plg_finder_products.sys.ini"
                        todir="${joomladir}/administrator/language/en-GB" />


                        
                <!-- plugins -->
                <!-- copy file="${src}/plugins/audio_jplayer/audio_jplayer.php"
                            todir="${joomladir}/plugins/mymuse/audio_jplayer" /> 
                <copy file="${src}/plugins/audio_jplayer/audio_jplayer.xml"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer" /> 
                <copy file="${src}/plugins/audio_jplayer/Jplayer.swf"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer" /> 
                <copy file="${src}/plugins/audio_jplayer/js/jplayer.playlist.min.js"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/js" /> 
                <copy file="${src}/plugins/audio_jplayer/js/jquery.jplayer.inspector.js"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/js" /> 
                <copy file="${src}/plugins/audio_jplayer/js/jquery.jplayer.min.js"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/js" /> 
                <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.css"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/skin" />
                 <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.orig.css"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/skin" />
                <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.rtl.css"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/skin" />
                <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.jpg"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/skin" />
                <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.seeking.gif"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/skin" />
                <copy file="${src}/plugins/audio_jplayer/skin/jplayer.blue.monday.video.play.png"
                                todir="${joomladir}/plugins/mymuse/audio_jplayer/skin" / -->

                <copy file="${src}/plugins/audio_amplitude/audio_amplitude.php"
                            todir="${joomladir}/plugins/mymuse/audio_amplitude" /> 
                <copy file="${src}/plugins/audio_amplitude/audio_amplitude.xml"
                            todir="${joomladir}/plugins/mymuse/audio_amplitude" /> 

                <copy file="${src}/plugins/storage_s3/storage_s3.php"
                            todir="${joomladir}/plugins/mymuse/storage_s3" /> 
                <copy file="${src}/plugins/storage_s3/storage_s3.xml"
                            todir="${joomladir}/plugins/mymuse/storage_s3" /> 
                <copy file="${src}/plugins/storage_s3/mymuseStorage.php"
                            todir="${joomladir}/plugins/mymuse/storage_s3" /> 

                <copy file="${src}/plugins/payment_stripeideal/payment_stripeideal.php"
                            todir="${joomladir}/plugins/mymuse/payment_stripeideal" /> 
                <copy file="${src}/plugins/payment_stripeideal/payment_stripeideal.xml"
                            todir="${joomladir}/plugins/mymuse/payment_stripeideal" /> 
                <copy file="${src}/plugins/payment_stripeideal/composer.json"
                            todir="${joomladir}/plugins/mymuse/payment_stripeideal" /> 
                <copy file="${src}/plugins/payment_stripeideal/composer.lock"
                            todir="${joomladir}/plugins/mymuse/payment_stripeideal" />
                <copy file="${src}/plugins/payment_stripeideal/language/en-GB/plg_mymuse_payment_stripeideal.ini"
                        todir="${joomladir}/administrator/language/en-GB" />
                <copy file="${src}/plugins/payment_stripeideal/language/en-GB/plg_mymuse_payment_stripeideal.sys.ini"
                        todir="${joomladir}/administrator/language/en-GB" />



                <copy file="${src}/plugins/user_mymuseuser/language/en-GB/plg_user_mymuseuser.ini"
                        todir="${joomladir}/administrator/language/en-GB" />
                <copy file="${src}/plugins/user_mymuseuser/language/en-GB/plg_user_mymuseuser.sys.ini"
                        todir="${joomladir}/administrator/language/en-GB" />
                <copy file="${src}/plugins/user_mymusenoreg/language/en-GB/plg_user_mymusenoreg.ini"
                        todir="${joomladir}/administrator/language/en-GB" />
                <copy file="${src}/plugins/user_mymusenoreg/language/en-GB/plg_user_mymusenoreg.sys.ini"
                        todir="${joomladir}/administrator/language/en-GB" />

                <copy file="${src}/plugins/user_mymuseuser/mymuseuser.xml"
                        todir="${joomladir}/plugins/user/mymuseuser" /> 
                <copy file="${src}/plugins/user_mymuseuser/mymuseuser.php"
                        todir="${joomladir}/plugins/user/mymuseuser" />
                <copy file="${src}/plugins/user_mymuseuser/forms/profile.xml"
                        todir="${joomladir}/plugins/user/mymuseuser/forms" />
                <copy file="${src}/plugins/user_mymuseuser/src/Field/TosField.php"
                            todir="${joomladir}/plugins/user/mymuseuser/src/Field" /> 
                
                <copy file="${src}/plugins/user_mymusenoreg/mymusenoreg.xml"
                            todir="${joomladir}/plugins/user/mymusenoreg" /> 
                <copy file="${src}/plugins/user_mymusenoreg/mymusenoreg.php"
                            todir="${joomladir}/plugins/user/mymusenoreg" />
                 <copy file="${src}/plugins/user_mymusenoreg/forms/profile.xml"
                            todir="${joomladir}/plugins/user/mymusenoreg/forms" />
                <copy file="${src}/plugins/user_mymusenoreg/src/Field/TosField.php"
                        todir="${joomladir}/plugins/user/mymusenoreg/src/Field" /> 

                <copy file="${src}/plugins/user_redirectonlogin/redirectonlogin.xml"
                            todir="${joomladir}/plugins/user/redirectonlogin" />
                <copy file="${src}/plugins/user_redirectonlogin/redirectonlogin.php"
                            todir="${joomladir}/plugins/user/redirectonlogin" />

                <copy file="${src}/plugins/mymuse_installer/mymuse_installer.xml"
                            todir="${joomladir}/plugins/installer/mymuse_installer" />
                <copy file="${src}/plugins/mymuse_installer/mymuse_installer.php"
                            todir="${joomladir}/plugins/installer/mymuse_installer" />


                <copy file="${src}/plugins/products/products.xml"
                            todir="${joomladir}/plugins/finder/products" /> 
                <copy file="${src}/plugins/products/services/provider.php"
                            todir="${joomladir}/plugins/finder/products/services" />
                 <copy file="${src}/plugins/products/src/Extension/Products.php"
                            todir="${joomladir}/plugins/finder/products/src/Extension" />

 

                <!--  modules -->
                <copy todir="${joomladir}/modules/mod_mymuse_minicart">
                        <fileset refid="mod_minicart_files" />
                </copy>

                <copy todir="${joomladir}/modules/mod_mymuse_amplitude">
                        <fileset refid="mod_amplitude_files" />
                </copy>

                <copy todir="${joomladir}/modules/mod_mymuse_latest">
                        <fileset refid="mod_latest_files" />
                </copy>

                <copy file="${src}/modules/mod_mymuse_latest/language/en-GB/mod_mymuse_latest.ini"
                        todir="${joomladir}/language/en-GB" />
                <copy file="${src}/modules/mod_mymuse_latest/language/en-GB/mod_mymuse_latest.sys.ini"
                        todir="${joomladir}/language/en-GB" />
        </target>
</project>
